# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serialization.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='serialization.proto',
  package='Pebble',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13serialization.proto\x12\x06Pebble\"\xce\x01\n\x0bTransaction\x12\x0e\n\x06txHash\x18\x01 \x01(\t\x12\x12\n\ncommitment\x18\t \x01(\x08\x12\x16\n\x0ePrimaryNodekey\x18\x02 \x01(\t\x12\x14\n\x0cNodeListSeed\x18\x03 \x01(\x05\x12\x16\n\x0eMultiSignature\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x03(\x05\x12\x15\n\rUserPublicKey\x18\x06 \x01(\t\x12\x1a\n\x12RecipientPublickey\x18\x07 \x01(\t\x12\x0f\n\x07payload\x18\x08 \x01(\x0c\"=\n\x11incominghandshake\x12\x18\n\x10sendingpublickey\x18\x01 \x01(\t\x12\x0e\n\x06nodeip\x18\x02 \x01(\t\"6\n\x11outgoinghandshake\x12\x11\n\tpublickey\x18\x01 \x03(\t\x12\x0e\n\x06nodeip\x18\x02 \x03(\tb\x06proto3')
)




_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='Pebble.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='txHash', full_name='Pebble.Transaction.txHash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commitment', full_name='Pebble.Transaction.commitment', index=1,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PrimaryNodekey', full_name='Pebble.Transaction.PrimaryNodekey', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NodeListSeed', full_name='Pebble.Transaction.NodeListSeed', index=3,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MultiSignature', full_name='Pebble.Transaction.MultiSignature', index=4,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Pebble.Transaction.timestamp', index=5,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UserPublicKey', full_name='Pebble.Transaction.UserPublicKey', index=6,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RecipientPublickey', full_name='Pebble.Transaction.RecipientPublickey', index=7,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='Pebble.Transaction.payload', index=8,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=238,
)


_INCOMINGHANDSHAKE = _descriptor.Descriptor(
  name='incominghandshake',
  full_name='Pebble.incominghandshake',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sendingpublickey', full_name='Pebble.incominghandshake.sendingpublickey', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodeip', full_name='Pebble.incominghandshake.nodeip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=301,
)


_OUTGOINGHANDSHAKE = _descriptor.Descriptor(
  name='outgoinghandshake',
  full_name='Pebble.outgoinghandshake',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='publickey', full_name='Pebble.outgoinghandshake.publickey', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodeip', full_name='Pebble.outgoinghandshake.nodeip', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=357,
)

DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
DESCRIPTOR.message_types_by_name['incominghandshake'] = _INCOMINGHANDSHAKE
DESCRIPTOR.message_types_by_name['outgoinghandshake'] = _OUTGOINGHANDSHAKE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION,
  '__module__' : 'serialization_pb2'
  # @@protoc_insertion_point(class_scope:Pebble.Transaction)
  })
_sym_db.RegisterMessage(Transaction)

incominghandshake = _reflection.GeneratedProtocolMessageType('incominghandshake', (_message.Message,), {
  'DESCRIPTOR' : _INCOMINGHANDSHAKE,
  '__module__' : 'serialization_pb2'
  # @@protoc_insertion_point(class_scope:Pebble.incominghandshake)
  })
_sym_db.RegisterMessage(incominghandshake)

outgoinghandshake = _reflection.GeneratedProtocolMessageType('outgoinghandshake', (_message.Message,), {
  'DESCRIPTOR' : _OUTGOINGHANDSHAKE,
  '__module__' : 'serialization_pb2'
  # @@protoc_insertion_point(class_scope:Pebble.outgoinghandshake)
  })
_sym_db.RegisterMessage(outgoinghandshake)


# @@protoc_insertion_point(module_scope)
